import Sorter from "./Sorter";
import Insertion from "./Insertion";
import Merge from "./Merge";
import MergeBU from "./MergeBU";
import Quick from "./Quick";
import Selection from "./Selection";
import Shell from "./Shell";
import QuickThree from "./QuickThree";
import Heap from "./Heap";
export default Sorter;
export { Insertion, Selection, Shell, Merge, MergeBU, Quick, QuickThree, Heap };
